# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivemee', '0024_auto_20160802_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(max_length=500)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='drivemee.Solicitud')),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
