# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivemee', '0026_auto_20161012_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='user',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
