# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivemee', '0027_auto_20161013_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='current_assignments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='max_assignments',
            field=models.IntegerField(default=1),
        ),
    ]
