# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivemee', '0028_auto_20161014_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('costo_variable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_fijo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo', models.CharField(choices=[(b'normal', b'Normal'), (b'tarde', b'\xc3\x9altima Semana'), (b'doble', b'Doble Cero')], default=b'normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_pagado', models.DateTimeField(blank=True)),
                ('notified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(b'pendiente', b'Pendiente'), (b'pagado', b'Pagado'), (b'error', b'Error')], default=b'pendiente', max_length=15)),
                ('conekta_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='force_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[(b'abierto', b'Abierto'), (b'preagendado', b'Pre-Agendado'), (b'agendado', b'Agendado'), (b'proceso', b'En Proceso'), (b'verificado', b'Verificado'), (b'cerrado', b'Concluido'), (b'caido', b'Cita Ca\xc3\xadda'), (b'cancelado', b'Cancelado'), (b'no_contratado', b'No Contratado'), (b'reagendado', b'Reagendado'), (b'pendiente', b'Pendiente'), (b'abandonada', b'Abandonada'), (b'porpagar', b'Pago Pendiente')], default=b'abierto', max_length=20),
        ),
        migrations.AddField(
            model_name='recibo',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='drivemee.Solicitud'),
        ),
    ]
