# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivemee', '0029_auto_20161122_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='timestamp_pagado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
