# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifica', '0027_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'verifica/clients/vehiculos/'),
        ),
    ]
