# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifica', '0028_vehiculo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='verifica.Client'),
        ),
    ]
