# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifica', '0029_auto_20160823_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accType', models.CharField(choices=[(b'free', b'Free User'), (b'paid', b'Paid User')], default=b'free', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('vigencia_licencia', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'verifica/clients/drivers/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='verifica.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.BooleanField(default=False)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('subType', models.CharField(choices=[(b'free', b'Free User'), (b'paid', b'Paid User')], default=b'free', max_length=20)),
                ('gps_token', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('gps_subscriptionId', models.TextField(blank=True, default=None, null=True)),
                ('gps_packageName', models.TextField(blank=True, default=None, null=True)),
                ('ios_receipt', models.TextField(blank=True, null=True)),
                ('ios_password', models.TextField(blank=True, default=None, null=True)),
                ('autoRenewing', models.BooleanField(default=False)),
                ('expiryTimeMillis', models.BigIntegerField(blank=True, null=True)),
                ('startTimeMillis', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accounttype',
            name='subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='verifica.Subscription'),
        ),
    ]
