# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifica', '0030_auto_20160825_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
