# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifica', '0031_vehiculo_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='accType',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subType',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='verifica.AccountType'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_source',
            field=models.CharField(choices=[(b'appstore', b'Apple App Store'), (b'playstore', b'Google Play Store'), (b'other', b'Other')], default=b'other', max_length=20),
        ),
    ]
